samples:
    - ggF
    - VBF
    - WH
    - ZH
    - ttH
    - WJetsLNu
    - TTbar
    - SingleTop
    - Diboson
    - EWKvjets
    - DYJets
    - WZQQ
    - Data

regions_sel:
    "Pre-selection": (THWW>0.50) & (rec_higgs_pt>250) & (fj_mass>40)

    "VBF": (THWW>0.905) & (n_bjets_T==0) & ( (mjj>1000) & (deta>3.5) ) & (rec_higgs_pt>250) & (fj_mass>40)
    "ggFpt250to300": (THWW>0.93) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>250) & (rec_higgs_pt<300) & (fj_mass>40)
    "ggFpt300to450": (THWW>0.93) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>300) & (rec_higgs_pt<450) & (fj_mass>40)
    "ggFpt450to650": (THWW>0.93) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>450) & (rec_higgs_pt<650) & (fj_mass>40)
    "ggFpt650toInf": (THWW>0.93) & (n_bjets_T==0) & ( (mjj<1000) | (deta<3.5) ) & (rec_higgs_pt>650) & (fj_mass>40)

    "WJetsCR": (THWW>0.50) & (THWW<0.905) & (n_bjets_T==0) & (rec_higgs_pt>250) & (fj_mass>40)
    "TopCR": (THWW>0.50) & (n_bjets_T>0) & (rec_higgs_pt>250) & (fj_mass>40)

samples_dir:
    "2018": ../eos/June25_hww_2018
    "2017": ../eos/June25_hww_2017
    "2016": ../eos/June25_hww_2016
    "2016APV": ../eos/June25_hww_2016APV

model_path: ../../weaver-core-dev/experiments_finetuning/v35_30/model.onnx
